### ISSUE TITLE
Dumb bot almost kill me

### ISSUE THREAD

**Issue by NOrma1cn** [w1ndys/W1ndysBotFrame#36]
Pls fix it and let it be smarter.As long as it is still dumb,both of us will doom.
- **Fake messages and lots of **shit** words.
- **No memory while chatting like a idiot.
- **It's developer tring to reviving the bot,joke.
- **At least it could work successfully,bruh.

**Comment by w1ndys** [comment]
Please Pull Request 👀

**Comment by NOrma1cn** [comment]
> 请 Pull Request 👀

That is the biggest joke i ve never seen before.

**Comment by NOrma1cn** [comment]
> 请 Pull Request 👀

Web crashed when i trying to pull requests.
